-- BCrypt hash of 'Password@123' (generated by the app)
UPDATE users 
SET password_hash = '$2a$10$PCsFY.o5lLCFZraDf5xBQOA9Q0uuSioJsKpkvFEnuUBC9GijOJtLO'
WHERE email IN (
  'recruiter1@recruitment.local',
  'recruiter2@recruitment.local',
  'candidate1@recruitment.local',
  'candidate2@recruitment.local',
  'candidate3@recruitment.local',
  'candidate4@recruitment.local',
  'candidate5@recruitment.local'
);

SELECT email, LEFT(password_hash, 25) AS hash_prefix FROM users ORDER BY id;
